default:
	@echo chess battle advanced

interpreter: interpreter.c Makefile
	gcc ./interpreter.c -o interpreter -O3 -Wall -Werror

translator: translator.c Makefile
	gcc ./translator.c -o translator -O3 -Wall -Werror